# ----
# Site

title: Instax365 by Grace
url: "https://www.instax365.com"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Photography for Fuji Instax Cameras.
author: 
  name: Grace
  email: 258282458@qq.com
  twitter: # twitter username without the @ symbol
social:
  name: Grace
  links:
    - https://www.instax365.com

image_process: ?imageView2/5/w/800/h/600/format/jpg/q/80

collections: 
  instaxdiaries:
    output: true

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true